In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/home/job_salary_prediction_dataset.csv')

In [3]:
df

,job_title,experience_years,education_level,skills_count,industry,company_size,location,remote_work,certifications,salary
0,AI Engineer,10,Bachelor,2,Healthcare,Medium,India,Hybrid,2,109413
1,Data Analyst,5,Bachelor,17,Telecom,Small,Australia,No,0,93764
2,Frontend Developer,18,PhD,4,Media,Medium,Singapore,No,1,148123
3,Business Analyst,19,PhD,13,Retail,Medium,Canada,Yes,0,189123
4,Product Manager,15,Bachelor,7,Manufacturing,Large,Sweden,Yes,0,165069
...,...,...,...,...,...,...,...,...,...,...
249995,Software Engineer,17,PhD,2,Telecom,Enterprise,India,No,1,127791
249996,Frontend Developer,20,PhD,7,Telecom,Startup,Remote,No,2,154593
249997,Business Analyst,1,Bachelor,12,Retail,Enterprise,India,Yes,0,75988
249998,Data Scientist,0,High School,2,Consulting,Small,Sweden,Hybrid,5,90467
249999,Data Analyst,16,Diploma,2,Technology,Medium,UK,No,5,133084

In [4]:
df.drop(['job_title', 'experience_years','skills_count','industry','location','certifications'], axis=1, inplace=True)

In [5]:
df

       education_level company_size remote_work  salary
0             Bachelor       Medium      Hybrid  109413
1             Bachelor        Small          No   93764
2                  PhD       Medium          No  148123
3                  PhD       Medium         Yes  189123
4             Bachelor        Large         Yes  165069
...                ...          ...         ...     ...
249995             PhD   Enterprise          No  127791
249996             PhD      Startup          No  154593
249997        Bachelor   Enterprise         Yes   75988
249998     High School        Small      Hybrid   90467
249999         Diploma       Medium          No  133084

[250000 rows x 4 columns]

In [6]:
df.isnull().sum()

education_level    0
company_size       0
remote_work        0
salary             0
dtype: int64

In [7]:
df['education_level'].value_counts()

education_level
Master         50352
High School    50065
Bachelor       49950
PhD            49857
Diploma        49776
Name: count, dtype: int64

In [8]:
df['company_size'].value_counts()

company_size
Large         50254
Small         50235
Medium        50027
Enterprise    49875
Startup       49609
Name: count, dtype: int64

In [9]:
df['remote_work'].value_counts()

remote_work
No        83621
Hybrid    83476
Yes       82903
Name: count, dtype: int64

In [10]:
df.dropna(inplace=True)

In [12]:
df.isnull().sum()

education_level    0
company_size       0
remote_work        0
salary             0
dtype: int64

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:3],df.iloc[:,-1],test_size=0.2,random_state=2)

In [14]:
X_train

       education_level company_size remote_work
86498           Master   Enterprise      Hybrid
163021          Master        Large         Yes
8878          Bachelor        Large      Hybrid
178333         Diploma        Large      Hybrid
125381         Diploma        Large          No
...                ...          ...         ...
175638             PhD        Small      Hybrid
95816      High School      Startup      Hybrid
203245         Diploma      Startup          No
100879             PhD        Large      Hybrid
89256              PhD        Small          No

[200000 rows x 3 columns]

In [15]:
y_train

86498     243183
163021    178425
8878      151554
178333    127873
125381    142454
           ...
175638    176760
95816     122447
203245    116652
100879    213288
89256     135531
Name: salary, Length: 200000, dtype: int64

In [19]:
from sklearn.preprocessing import OrdinalEncoder

In [20]:
oe = OrdinalEncoder(categories=[['High School','Diploma','Bachelor','Master','PhD'],['Startup','Small','Medium','Large','Enterprise'],['No','Hybrid','Yes']])

In [21]:
# Step 1: Fit
oe.fit(X_train)

OrdinalEncoder(categories=[['High School', 'Diploma', 'Bachelor', 'Master',
                            'PhD'],
                           ['Startup', 'Small', 'Medium', 'Large',
                            'Enterprise'],
                           ['No', 'Hybrid', 'Yes']])

In [22]:
# Step 1: Transform
X_train = oe.transform(X_train)

In [23]:
oe.categories_

[array(['High School', 'Diploma', 'Bachelor', 'Master', 'PhD'],
       dtype=object),
 array(['Startup', 'Small', 'Medium', 'Large', 'Enterprise'], dtype=object),
 array(['No', 'Hybrid', 'Yes'], dtype=object)]

In [24]:
X_train

array([[3., 4., 1.],
       [3., 3., 2.],
       [2., 3., 1.],
       ...,
       [1., 0., 0.],
       [4., 3., 1.],
       [4., 1., 0.]])