In [8]:
import pandas as pd
import numpy as np
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler

In [9]:
data = {
    "Age": [25, 30, 35, 40, np.nan],
    "Salary": [50000, 60000, np.nan, 80000, 75000],
    "Experience": [2, 5, 7, np.nan, 6]
}

df = pd.DataFrame(data)

In [10]:
df

    Age   Salary  Experience
0  25.0  50000.0         2.0
1  30.0  60000.0         5.0
2  35.0      NaN         7.0
3  40.0  80000.0         NaN
4   NaN  75000.0         6.0

In [11]:
# Scaling  Apply
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

In [14]:
#Iterative Imputer apply
imputer = IterativeImputer( max_iter=10,random_state=42)
df_imputed = imputer.fit_transform(df_scaled)

df_imputed = pd.DataFrame(df_imputed, columns=df.columns)

In [15]:
df_imputed

        Age    Salary  Experience
0 -1.341641 -1.362770   -1.603567
1 -0.447214 -0.524142    0.000000
2  0.447214  0.314477    1.069045
3  1.341641  1.153113    1.417866
4  0.894368  0.733799    0.534522