In [7]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.impute import KNNImputer

In [8]:
data = {
    "Age": [25, 30, 35, 40, np.nan],
    "Salary": [50000, 60000, np.nan, 80000, 75000],
    "Experience": [2, 5, 7, np.nan, 6]
}

df = pd.DataFrame(data)

In [9]:
df

    Age   Salary  Experience
0  25.0  50000.0         2.0
1  30.0  60000.0         5.0
2  35.0      NaN         7.0
3  40.0  80000.0         NaN
4   NaN  75000.0         6.0

In [12]:

# Scaling  Apply
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df)

In [13]:
df_scaled

array([[-1.34164079, -1.36277029, -1.60356745],
       [-0.4472136 , -0.52414242,  0.        ],
       [ 0.4472136 ,         nan,  1.06904497],
       [ 1.34164079,  1.15311332,         nan],
       [        nan,  0.73379939,  0.53452248]])

In [15]:


# Create imputer object
imputer = KNNImputer(n_neighbors=2)

# Apply imputation
df_imputed = imputer.fit_transform(df_scaled)

# Convert back to DataFrame
df_imputed = pd.DataFrame(df_imputed, columns=df.columns)

In [16]:
df_imputed

        Age    Salary  Experience
0 -1.341641 -1.362770   -1.603567
1 -0.447214 -0.524142    0.000000
2  0.447214  0.943456    1.069045
3  1.341641  1.153113    0.801784
4  0.894427  0.733799    0.534522