In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:

data = {
    'Age': [24, 26, 28, 27, np.nan, 29, 30, np.nan],
    'Salary': [40000, 42000, 45000, 43000, np.nan, 47000, 48000, np.nan],
    'Experience': [1, 2, 3, 2, np.nan, 4, 5, np.nan]
}

In [17]:
df = pd.DataFrame(data)

In [15]:
df

    Age    Salary  Experience
0  25.0   50000.0         2.0
1  30.0   60000.0         5.0
2   NaN   55000.0         3.0
3  22.0       NaN         1.0
4  28.0   58000.0         NaN
5  35.0  120000.0        10.0
6   NaN  130000.0        12.0
7  40.0       NaN         NaN

In [19]:
df.isnull().sum()

Age           2
Salary        2
Experience    2
dtype: int64

In [21]:
df_mean = df.copy()

df_mean['Age'] = df_mean['Age'].fillna(df_mean['Age'].mean())
df_mean['Salary'] = df_mean['Salary'].fillna(df_mean['Salary'].mean())
df_mean['Experience'] = df_mean['Experience'].fillna(df_mean['Experience'].mean())

In [22]:

df_mean

         Age        Salary  Experience
0  24.000000  40000.000000    1.000000
1  26.000000  42000.000000    2.000000
2  28.000000  45000.000000    3.000000
3  27.000000  43000.000000    2.000000
4  27.333333  44166.666667    2.833333
5  29.000000  47000.000000    4.000000
6  30.000000  48000.000000    5.000000
7  27.333333  44166.666667    2.833333

###Using SkLearn

In [9]:
from sklearn.impute import SimpleImputer

# Create imputer object
mean_imputer = SimpleImputer(strategy='mean')

# Apply on numerical columns
df_meanskLearn = pd.DataFrame(mean_imputer.fit_transform(df), columns=df.columns)

In [11]:
df_meanskLearn.isnull().sum()

Age           0
Salary        0
Experience    0
dtype: int64