In [3]:
import pandas as pd
import numpy as np
from scipy import stats

###Create sample data:

In [4]:


data = {
    'marks': [40, 42, 45, 47, 50, 52, 100]  # 100 is an outlier
}
df = pd.DataFrame(data)
print(df)

   marks
0     40
1     42
2     45
3     47
4     50
5     52
6    100

In [5]:
df['marks'].describe()

count      7.000000
mean      53.714286
std       20.838380
min       40.000000
25%       43.500000
50%       47.000000
75%       51.000000
max      100.000000
Name: marks, dtype: float64

###Calculate Z-score:

In [ ]:
mean = df['marks'].mean()
std = df['marks'].std()

df['z_score_manual'] = (df['marks'] - mean) / std

print(df)

   marks  z_score_manual
0     40       -0.658126
1     42       -0.562150
2     45       -0.418184
3     47       -0.322208
4     50       -0.178243
5     52       -0.082266
6    100        2.221176

In [ ]:
df['z_score'] = stats.zscore(df['marks'])

In [ ]:
df['z_score']

0   -0.710858
1   -0.607191
2   -0.451691
3   -0.348024
4   -0.192524
5   -0.088857
6    2.399144
Name: z_score, dtype: float64

###Detect outliers:

In [ ]:


outliers = df[np.abs(df['z_score']) > 3]
print("Outliers:\n", outliers)

Outliers:
 Empty DataFrame
Columns: [marks, z_score_manual, z_score]
Index: []

###Remove outliers:

In [ ]:


df_clean = df[np.abs(df['z_score']) <= 3]
print("Clean Data:\n", df_clean)

Clean Data:
      marks  z_score_manual   z_score
0       40       -0.353592 -0.378006
1       42       -0.353587 -0.378000
2       45       -0.353578 -0.377991
3       47       -0.353572 -0.377985
4       50       -0.353564 -0.377976
5       52       -0.353558 -0.377970
6      100       -0.353422 -0.377825
7  1000000        2.474874  2.645751